# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestPassport():
  def setup_method(self, method):
    self.driver = webdriver.Chrome()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_passport(self):
    self.driver.get("https://qa.neapro.site/login")
    self.driver.find_element(By.CSS_SELECTOR, ".fieldset:nth-child(1) input").click()
    self.driver.find_element(By.CSS_SELECTOR, ".fieldset:nth-child(1) input").send_keys("dkopylova@list.ru")
    self.driver.find_element(By.CSS_SELECTOR, ".fieldset:nth-child(2) input").send_keys("123456")
    self.driver.find_element(By.CSS_SELECTOR, ".btn").click()
    self.driver.find_element(By.CSS_SELECTOR, ".active .document-tile:nth-child(1) > .document-name").click()
    self.driver.find_element(By.ID, "surname").send_keys("Иванов")
    self.driver.find_element(By.ID, "name").send_keys("Иван")
    self.driver.find_element(By.ID, "patronymic").click()
    self.driver.find_element(By.ID, "patronymic").click()
    self.driver.find_element(By.ID, "patronymic").send_keys("Иванович")
    self.driver.find_element(By.CSS_SELECTOR, "#birthday svg").click()
    self.driver.find_element(By.CSS_SELECTOR, "tbody").click()
    self.driver.find_element(By.CSS_SELECTOR, ".mx-date-row:nth-child(1) > .cell:nth-child(5) > div").click()
    self.driver.find_element(By.ID, "passportSeries").click()
    self.driver.find_element(By.ID, "passportSeries").send_keys("11-11")
    self.driver.find_element(By.ID, "passportNumber").send_keys("111111")
    self.driver.find_element(By.CSS_SELECTOR, ".active .document-tile:nth-child(1) > .document-name").click()
    self.driver.find_element(By.CSS_SELECTOR, "#dateOfIssue svg").click()
    self.driver.find_element(By.CSS_SELECTOR, ".mx-date-row:nth-child(1) > .cell:nth-child(6) > div").click()
    self.driver.find_element(By.ID, "code").click()
    self.driver.find_element(By.ID, "code").send_keys("111-111")
    self.driver.find_element(By.ID, "cardId").send_keys("111-111-111 11")
    self.driver.find_element(By.ID, "issued").send_keys("аааааааааааа")
    self.driver.find_element(By.CSS_SELECTOR, ".vue-dadata__input").send_keys("Алтайский край, г. Бийск, ул. Береговая, д 1")
    self.driver.find_element(By.ID, "phone").send_keys("1111111111")
  
